function teraterm = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  TERATERM = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  TERATERM = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  teraterm = importfile("G:\Vietnam\Daten\Grimm\teraterm.log", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 30-Sep-2020 16:09:30

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 20);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = [" ", "  ", "   ", "    "];

% Specify column names and types
opts.VariableNames = ["P", "year", "month", "day", "hour", "minute", "loc", "gf", "er", "qbatt", "im", "uel", "ue4", "ue3", "ue2", "ue1", "iv", "ka1", "ka2", "VarName20"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["P", "VarName20"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["P", "VarName20"], "EmptyFieldRule", "auto");

% Import the data
teraterm = readtable(filename, opts);

end