function Wasserbilanzdat = readWasserbilanzdat(filename, dataLines)
%IMPORTFILE Import data from a text file
%  WASSERBILANZOBST = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  WASSERBILANZOBST = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  WasserbilanzOBST = importfile("D:\LVA\BSc_Hydrologie\Übung Hydrologie\Übung\1_einzugsgebiete_HQ-wasserbilanz\Wasserbilanz_OBST.csv", [8, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 18-Oct-2021 18:10:34

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [8, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Datum", "Zeit", "N", "Q"];
opts.VariableTypes = ["datetime", "datetime", "double", "double"];
opts = setvaropts(opts, 1, "InputFormat", "dd.MM.yyyy");
opts = setvaropts(opts, 2, "InputFormat", "HH:mm");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Wasserbilanzdat = readtable(filename, opts);

end